project 'VoxeetUXKitSampleCocoaPods.xcodeproj'

platform :ios, '12.0'

target 'VoxeetUXKitSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VoxeetUXKitSample
  pod 'VoxeetUXKit', :path => '../'
end
