// Generated by Apple Swift version 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_attribute(external_source_symbol)
# define SWIFT_STRINGIFY(str) #str
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name) _Pragma(SWIFT_STRINGIFY(clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in=module_name, generated_declaration))), apply_to=any(function, enum, objc_interface, objc_category, objc_protocol))))
# define SWIFT_MODULE_NAMESPACE_POP _Pragma("clang attribute pop")
#else
# define SWIFT_MODULE_NAMESPACE_PUSH(module_name)
# define SWIFT_MODULE_NAMESPACE_POP
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import Foundation;
@import ObjectiveC;
#endif

#import <VoxeetSDK/VoxeetSDK.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

SWIFT_MODULE_NAMESPACE_PUSH("VoxeetSDK")









SWIFT_CLASS("_TtC9VoxeetSDK12VTAudioSound")
@interface VTAudioSound : NSObject
/// If true, looping on the current sound.
@property (nonatomic) BOOL loop;
/// The volume of the audio file. The range of valid values are from 0.0 to 1.0.
@property (nonatomic) float volume;
/// The angle of the audio file. The range of valid values are from -1.0 to 1.0.
@property (nonatomic) float angle;
/// The distance of the audio file. The range of valid values are from 0.0 to 1.0.
@property (nonatomic) float distance;
/// Initializing a new VTAudioSound. The audio file must be mono to get a 3D mixing properties.
/// \param fileURL File path URL.
///
- (nullable instancetype)initWithFileURL:(NSURL * _Nonnull)url error:(NSError * _Nullable * _Nullable)error OBJC_DESIGNATED_INITIALIZER;
/// Initializing a new VTAudioSound. The audio file must be mono to get a 3D mixing properties.
/// \param forResource File’s name.
///
/// \param ofType File’s extension (mp3, wav, …).
///
- (nullable instancetype)initForResource:(NSString * _Nonnull)name ofType:(NSString * _Nonnull)ext error:(NSError * _Nullable * _Nullable)error;
/// Play the audio file.
/// \param completion A block object to be executed when the sound has finished playing. This block has no return value.
///
- (BOOL)playAndReturnError:(NSError * _Nullable * _Nullable)error completion:(void (^ _Nullable)(void))completion;
/// Stop the audio file.
- (void)stop;
/// Get the current time of the playing sound.
///
/// returns:
/// current time in second
- (double)currentTime SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@protocol VTConferenceDelegate;
@class VTUser;
enum VTConferenceState : NSInteger;

SWIFT_CLASS("_TtC9VoxeetSDK12VTConference")
@interface VTConference : NSObject
/// Conference delegate.
@property (nonatomic, weak) id <VTConferenceDelegate> _Nullable delegate;
/// Getting live conference ID (Voxeet internal identifier). If <code>nil</code> there isn’t any current conference.
@property (nonatomic, readonly, copy) NSString * _Nullable id;
/// Getting the live conference alias. If <code>nil</code> there isn’t any current conference.
@property (nonatomic, readonly, copy) NSString * _Nullable alias;
/// Gettings all current conference’s users.
@property (nonatomic, readonly, copy) NSArray<VTUser *> * _Nonnull users;
@property (nonatomic, readonly) enum VTConferenceState state;
@property (nonatomic, readonly, strong) VTUser * _Nullable ownUser;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end

@class MediaStream;

@interface VTConference (SWIFT_EXTENSION(VoxeetSDK)) <MediaAPIDelegate>
- (void)streamAddedForPeer:(NSString * _Nonnull)peerId withStream:(MediaStream * _Nonnull)mediaStream;
- (void)streamUpdatedForPeer:(NSString * _Null_unspecified)peerId withStream:(MediaStream * _Null_unspecified)mediaStream;
- (void)streamRemovedForPeer:(NSString * _Nonnull)peerId withStream:(MediaStream * _Nonnull)mediaStream;
- (void)screenShareStreamAddedForPeer:(NSString * _Nonnull)peerId withStream:(MediaStream * _Nonnull)mediaStream;
- (void)screenShareStreamRemovedForPeer:(NSString * _Nonnull)peerId withStream:(MediaStream * _Nonnull)mediaStream;
@end


@interface VTConference (SWIFT_EXTENSION(VoxeetSDK))
/// Creating Voxeet demo conference.
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)demoWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Manually create a conference (the join method implicitly creates one if it’s not already created).
/// \param parameters You can optionally pass some parameters when you create a conference such as <code>conferenceAlias</code> (example: <code>["conferenceAlias": "myCustomConferenceAlias", "conferenceType": "standard", "metadata": ...]</code>). Those parameters are specific to a conference (not to be confused with userInfo).
///
/// \param success A block object to be executed when the server connection sequence ends. This block has no return value and takes a <code>[String: Any]?</code> argument which correspond to a JSON object.
///
/// \param fail A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)createWithParameters:(NSDictionary<NSString *, id> * _Nullable)parameters success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nullable))successCompletion fail:(void (^ _Nullable)(NSError * _Nonnull))failCompletion;
/// Invite some users in a conference.
/// \param conferenceID Conference ID.
///
/// \param ids User’s ids to invite.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)inviteWithConferenceID:(NSString * _Nonnull)confID ids:(NSArray<NSString *> * _Nonnull)ids completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Joining a conference with an ID (if the conference isn’t created yet, this method will automatically create a new one and joint it).
/// \param conferenceID Conference identifier retrieved from create response (also compatible with conference alias).
///
/// \param video Starts own video when launching the conference (false by default).
///
/// \param userInfo With this dictionary, you can pass additional information linked to your user. For example if the user is only in “listener” mode you can add: <code>["participantType": "listener"]</code>. Other examples: <code>["externalName": "User", "externalPhotoUrl": "http://voxeet.com/voxeet-logo.jpg", ...]</code>.
///
/// \param success A block object to be executed when the server connection sequence ends. This block has no return value and takes a <code>[String: Any]?</code> argument which correspond to a JSON object.
///
/// \param fail A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)joinWithConferenceID:(NSString * _Nonnull)confID video:(BOOL)video userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nullable))successCompletion fail:(void (^ _Nullable)(NSError * _Nonnull))failCompletion;
/// Leaving the current conference.
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)leaveWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
- (void)declineWithConferenceID:(NSString * _Nonnull)confID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Sending broadcast message to the current conference.
/// \param message The string message that will be sent to the current conference.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)broadcastWithMessage:(NSString * _Nonnull)message completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Getting a specific conference status.
/// \param conferenceID Conference ID.
///
/// \param success A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>[String: Any]?</code> argument which correspond to a JSON object.
///
/// \param fail A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)statusWithConferenceID:(NSString * _Nonnull)confID success:(void (^ _Nullable)(NSDictionary<NSString *, id> * _Nullable))successCompletion fail:(void (^ _Nullable)(NSError * _Nonnull))failCompletion;
/// Subscribe to a conference to get its status within a notification (the conference needs to be created before using this method).
/// \param conferenceID Conference ID.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)subscribeWithConferenceID:(NSString * _Nonnull)confID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Getting the history of a specific conference.
/// \param conferenceID Conference ID.
///
/// \param success A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>[Any]?</code> argument which correspond to a JSON object.
///
/// \param fail A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)historyWithConferenceID:(NSString * _Nonnull)confID success:(void (^ _Nullable)(NSArray * _Nullable))successCompletion fail:(void (^ _Nullable)(NSError * _Nonnull))failCompletion;
/// Getting own conference histories. You can retrieve 0 to 40 events per pages.
/// \param nbEvents Number of meetings wanted (0-40).
///
/// \param lastConferenceID Use (lastMeetingId & lastTimestamp) to handle paging.
///
/// \param lastConferenceTimestamp Use (lastMeetingId & lastTimestamp) to handle paging.
///
/// \param success A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>[Any]?</code> argument which correspond to a JSON object.
///
/// \param fail A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)historiesWithNbEvents:(NSInteger)nbEvents lastConferenceID:(NSString * _Nullable)confID lastConferenceTimestamp:(int64_t)timestamp success:(void (^ _Nullable)(NSArray * _Nullable))successCompletion fail:(void (^ _Nullable)(NSError * _Nonnull))failCompletion;
/// Getting own conference histories. You can retrieve 0 to 40 events per pages.
/// \param nbEvents Number of meetings wanted (0-40).
///
/// \param success A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>[Any]?</code> argument which correspond to a JSON object.
///
/// \param fail A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)historiesWithNbEvents:(NSInteger)nbEvents success:(void (^ _Nullable)(NSArray * _Nullable))successCompletion fail:(void (^ _Nullable)(NSError * _Nonnull))failCompletion;
/// Start recording the current conference.
/// \param conferenceID Conference ID.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)startRecordingWithConferenceID:(NSString * _Nonnull)confID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Stop recording (need to start a record with <code>startRecording</code> method before stopping it).
/// \param conferenceID Conference ID.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)stopRecordingWithConferenceID:(NSString * _Nonnull)confID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Replay a recording conference (need to start and stop a record before).
/// \param conferenceID Conference ID (do not pass an alias, only the voxeet conference UUID returned by the join method for example).
///
/// \param offset You can start the recording after an offset in millisecond. For example if you pass 1000ms, the conference will jump the first second.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)replayWithConferenceID:(NSString * _Nonnull)confID offset:(NSInteger)offset completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Replay a recording conference (need to start and stop a record before).
/// \param conferenceID Conference ID (do not pass an alias, only the voxeet conference UUID returned by the join method for example).
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)replayWithConferenceID:(NSString * _Nonnull)confID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end

@class VideoRenderer;

@interface VTConference (SWIFT_EXTENSION(VoxeetSDK))
/// Getting the live conference ID. If <code>nil</code> there is no current conference.
///
/// returns:
/// current conference ID.
- (NSString * _Nullable)liveConferenceID SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("Has been renamed as `VoxeetSDK.shared.conference.id`", "id");
/// Getting a specific user.
/// \param userID User ID.
///
///
/// returns:
/// a <code>VTUser</code> object.
- (VTUser * _Nullable)userWithUserID:(NSString * _Nonnull)userID SWIFT_WARN_UNUSED_RESULT;
/// Changing the user position.
/// \param userID User ID.
///
/// \param angle Changes the user position with an angle.
///
/// \param distance Changes the user position with a distance.
///
- (void)userPositionWithUserID:(NSString * _Nonnull)userID angle:(double)angle distance:(double)distance;
/// Changing the user position (with just an angle, see <code>setUserPosition(userID: String, angle: Double, distance: Double)</code>).
/// \param userID User ID.
///
/// \param angle Changes the user position with an angle.
///
- (void)userPositionWithUserID:(NSString * _Nonnull)userID angle:(double)angle;
/// Changing the user position (with just a distance, see <code>setUserPosition(userID: String, angle: Double, distance: Double)</code>).
/// \param userID User ID.
///
/// \param distance Changes the user position with a distance.
///
- (void)userPositionWithUserID:(NSString * _Nonnull)userID distance:(double)distance;
/// Muting / unmuting a user.
/// \param userID User ID.
///
/// \param isMuted Mute or unmute a user.
///
- (void)muteWithUserID:(NSString * _Nonnull)userID isMuted:(BOOL)isMuted;
/// Toggle muting / Unmuting on a user.
/// \param userID User ID.
///
///
/// returns:
/// mute state.
- (BOOL)toggleMuteWithUserID:(NSString * _Nonnull)userID SWIFT_WARN_UNUSED_RESULT;
/// Switching between BuiltInSpeaker and BuildInReceiver.
- (void)switchDeviceSpeaker;
/// Switching between BuiltInSpeaker and BuildInReceiver.
/// \param forceBuiltInSpeaker Forces the audio to get set on the main speaker if <code>true</code>. If the value is <code>false</code> the buildInReceiver will be forced.
///
- (void)switchDeviceSpeakerWithForceBuiltInSpeaker:(BOOL)forceBuiltInSpeaker;
/// Attaching a media stream to a renderer.
/// \param stream Stream to be rendered into the view.
///
/// \param renderer The view renderer that will display the video.
///
- (void)attachMediaStream:(MediaStream * _Nonnull)stream renderer:(VideoRenderer * _Nonnull)renderer;
/// Unattaching a media stream to a renderer.
/// \param stream Stream to be rendered into the view.
///
/// \param renderer The view renderer that will display the video.
///
- (void)unattachMediaStream:(MediaStream * _Nullable)stream renderer:(VideoRenderer * _Nonnull)renderer;
/// Getting the users’s voice level.
/// \param userID User ID.
///
///
/// returns:
/// the current voice level of a user.
- (double)voiceLevelWithUserID:(NSString * _Nonnull)userID SWIFT_WARN_UNUSED_RESULT;
/// Flipping the device camera (front/back).
- (void)flipCamera;
/// Starting a video stream for a specific user.
/// \param userID User ID.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)startVideoWithUserID:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Stopping a video stream for a specific user.
/// \param userID User ID.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)stopVideoWithUserID:(NSString * _Nonnull)userID completion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end


SWIFT_PROTOCOL("_TtP9VoxeetSDK20VTConferenceDelegate_")
@protocol VTConferenceDelegate
@optional
- (void)participantAddedWithUserID:(NSString * _Nonnull)userID userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo stream:(MediaStream * _Nonnull)stream;
- (void)participantUpdatedWithUserID:(NSString * _Nonnull)userID userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo stream:(MediaStream * _Nonnull)stream;
- (void)participantRemovedWithUserID:(NSString * _Nonnull)userID userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo;
- (void)messageReceivedWithUserID:(NSString * _Nonnull)userID userInfo:(NSDictionary<NSString *, id> * _Nonnull)userInfo message:(NSString * _Nonnull)message;
- (void)screenShareStartedWithUserID:(NSString * _Nonnull)userID stream:(MediaStream * _Nonnull)stream;
- (void)screenShareStoppedWithUserID:(NSString * _Nonnull)userID;
@end

typedef SWIFT_ENUM(NSInteger, VTConferenceState) {
  VTConferenceStateConnecting = 0,
  VTConferenceStateConnected = 1,
  VTConferenceStateDisconnecting = 2,
  VTConferenceStateDisconnected = 3,
};

enum VTSessionState : NSInteger;
@protocol VTSessionDelegate;

SWIFT_CLASS("_TtC9VoxeetSDK9VTSession")
@interface VTSession : NSObject
/// Current session user.
@property (nonatomic, readonly, strong) VTUser * _Nullable user;
/// Getting current session state.
@property (nonatomic, readonly) enum VTSessionState state;
/// Session delegate.
@property (nonatomic, strong) id <VTSessionDelegate> _Nullable delegate;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


@interface VTSession (SWIFT_EXTENSION(VoxeetSDK))
/// Connecting the SDK with the API (manually).
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)connectWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Manually connect the session is like a login. However you need to have initialized the SDK with connectSession sets to false. By passing the userID, it will log your user into our servers with your ID (you can additionally pass some extra information with the <code>userInfo</code> parameter). This method can be useful if you want to implement CallKit (VoIP push notifications) because once you openned a session, you can receive notifications. If you don’t open a session it will automatically openning a new one when joinning a conference for example.
/// \param userID User ID is linked to our server’s users.
///
/// \param userInfo Some additional information can be linked to a user. Here are some examples: <code>["externalName": "User", "externalPhotoUrl": "http://voxeet.com/voxeet-logo.jpg", ...]</code>.
///
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)connectWithUserID:(NSString * _Nonnull)userID userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo completion:(void (^ _Nullable)(NSError * _Nullable))completion;
/// Disonnecting the SDK with the API (manually). Closing a session is like a logout, it will stop the socket and stop sending VoIP push notification.
/// \param completion A block object to be executed when the server connection sequence ends. This block has no return value and takes a single <code>NSError</code> argument that indicates whether or not the connection to the server succeeded.
///
- (void)disconnectWithCompletion:(void (^ _Nullable)(NSError * _Nullable))completion;
@end


SWIFT_PROTOCOL("_TtP9VoxeetSDK17VTSessionDelegate_")
@protocol VTSessionDelegate
- (void)sessionUpdatedWithState:(enum VTSessionState)state;
@end

typedef SWIFT_ENUM(NSInteger, VTSessionState) {
  VTSessionStateConnecting = 0,
  VTSessionStateConnected = 1,
  VTSessionStateReconnecting = 2,
  VTSessionStateDisconnected = 3,
};

@class VTUserConferenceInfo;

SWIFT_CLASS("_TtC9VoxeetSDK6VTUser")
@interface VTUser : NSObject
/// User’s identifier.
@property (nonatomic, copy) NSString * _Nullable id;
/// User’s information.
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull info;
/// User conference’s information.
@property (nonatomic, readonly, strong) VTUserConferenceInfo * _Nonnull conferenceInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC9VoxeetSDK20VTUserConferenceInfo")
@interface VTUserConferenceInfo : NSObject
@property (nonatomic, readonly) double angle;
@property (nonatomic, readonly) double distance;
@property (nonatomic, readonly) BOOL mute;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC9VoxeetSDK9VoxeetSDK")
@interface VoxeetSDK : NSObject
/// Voxeet SDK singleton.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) VoxeetSDK * _Nonnull shared;)
+ (VoxeetSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
/// Session (socket related).
@property (nonatomic, readonly, strong) VTSession * _Nonnull session;
/// Conference manager.
@property (nonatomic, readonly, strong) VTConference * _Nonnull conference;
/// Includes CallKit calls in the system’s Recents list at the end of each call if true (available for iOS 11 or higher).
@property (nonatomic) BOOL includesCallsInRecents;
/// By default the SDK start on the built in receiver (phone one). If true it will start on the main speaker.
@property (nonatomic) BOOL defaultBuiltInSpeaker;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@end






@interface VoxeetSDK (SWIFT_EXTENSION(VoxeetSDK))
/// Initializing the Voxeet SDK (this method doesn’t automatically open the session).
/// \param consumerKey To get a consumer key, you need to contact Voxeet in order to use the Voxeet SDK.
///
/// \param consumerSecret To get a consumer secret, you need to contact Voxeet in order to use the Voxeet SDK.
///
/// \param userInfo With this dictionary, you can pass additional information. For example you can add any data you want to initialize a user: <code>["externalId": "1234", "externalName": "User", "externalPhotoUrl": "http://voxeet.com/voxeet-logo.jpg", ...]</code>.
///
- (void)initializeWithConsumerKey:(NSString * _Nonnull)consumerKey consumerSecret:(NSString * _Nonnull)consumerSecret userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo;
/// Initializing the Voxeet SDK.
/// \param consumerKey To get a consumer key, you need to contact Voxeet in order to use the Voxeet SDK.
///
/// \param consumerSecret To get a consumer secret, you need to contact Voxeet in order to use the Voxeet SDK.
///
/// \param userInfo With this dictionary, you can pass additional information. For example you can add any data you want to initialize a user: <code>["externalId": "1234", "externalName": "User", "externalPhotoUrl": "http://voxeet.com/voxeet-logo.jpg", ...]</code>.
///
/// \param callKit Enable or disable CallKit (VoIP needs to be enable in application’s capabilities too).
///
/// \param connectSession You may want to manage your user identifier and information like a classic login. You can connect your session later by setting this parameter to false and call <code>VoxeetSDK.shared.session.connect(userID:userInfo:completion:)</code>. If true, the SDK will automatically connect your user (anonymously identified if <code>userInfo</code> parameter is empty). Only works if <code>callKit</code> is activated and push notifications capability ON.
///
- (void)initializeWithConsumerKey:(NSString * _Nonnull)consumerKey consumerSecret:(NSString * _Nonnull)consumerSecret userInfo:(NSDictionary<NSString *, id> * _Nullable)userInfo callKit:(BOOL)callKit connectSession:(BOOL)connectSession;
@end

SWIFT_MODULE_NAMESPACE_POP
#pragma clang diagnostic pop
