//
//  Bundle+Extension.swift
//  VoxeetUXKit
//
//  Created by Zugaj, Edyta on 16/02/2022.
//  Copyright © 2022 Voxeet. All rights reserved.
//

#if !SWIFT_PACKAGE
// Based on resource_bundle_accessor.swift generated by xcode for Swift package.

import class Foundation.Bundle

private class BundleFinder {}

extension Foundation.Bundle {
    /// Returns the resource bundle associated with the current Swift module.
    static var module: Bundle = {
        let bundleName = "VoxeetUXKit_VoxeetUXKit"
        let candidates = [
            // Bundle should be present here when the package is linked into an App.
            Bundle.main.resourceURL,

            // Bundle should be present here when the package is linked into a framework.
            Bundle(for: BundleFinder.self).resourceURL,

            // For command-line tools.
            Bundle.main.bundleURL,
        ]
        for candidate in candidates {
            let bundlePath = candidate?.appendingPathComponent(bundleName + ".bundle")
            if let bundle = bundlePath.flatMap(Bundle.init(url:)) {
                return bundle
            }
        }
        
        return Bundle(for: BundleFinder.self)
    }()
}
#endif
